### ISSUE TITLE
understanding that client is disconnected from server

### ISSUE THREAD

**Issue by A-H-B-Gh** [RevenantX/LiteNetLib#88] opened 2017-08-23 08:41 UTC
Hello again 😁
I am building realtime game that two player in same time play with each other. So I store Netpeers and if I found two client are requesting for game at same time I will put them in one game. But the problem is that i can't undresstand if one user is compeletly disconnected. Is there any way to undresstand that one netpeer is still connected without using new api?

**Comment by marsermd** [comment] 2017-08-23 09:34
Hi! 
Why don't `EventBasedNetListener.PeerConnectedEvent` and `EventBasedNetListener.PeerDisconnectedEvent` satisfy your needs?

If PeerConnectedEvent was called and PeerDisconnectedEvent wasn't, peer is connected.

If you want to get all connected peers, you have `NetManager.GetPeers()` and it's non-allocating version `NetManager.GetPeersNonAlloc(List<NetPeer>)`

**Comment by RevenantX** [comment] 2017-08-23 10:43
@A-H-B-Gh there is NetPeer.ConnectionState:
```csharp
/// <summary>
/// Peer connection state
/// </summary>
public enum ConnectionState
{
    InProgress,
    Connected,
    Disconnected
}
```
```csharp
class NetPeer
{
//...
    /// <summary>
    /// Current connection state
    /// </summary>
    public ConnectionState ConnectionState
    {
        get { return _connectionState; }
    }
//...
```

**Comment by A-H-B-Gh** [comment] 2017-08-24 08:12
when I call `NetManager.DisconnectPeer(Netpeer client)` in the client I can use the `PeerConnectedEvent ` and `PeerDisconnectedEvent` but when the client force the game to stop and doesn't let the client to send disconnect event the connection state in server doesn't change and so GetPeers() has one client that is disconnected and we don't know that.  
thanks for your fast reply :)

**Comment by RevenantX** [comment] 2017-08-24 09:33
@A-H-B-Gh 
NetManager.DisconnectTimeout
if client or server doesn't receive any packet from remote peer during this time then connection will be closed
(including library internal keepalive packets)
default value: 5000 msec.

You can reduce that value for your needs.

**Comment by A-H-B-Gh** [comment] 2017-08-24 10:10
something really strange about unity editor : 
I had a C# code in unity. I stop the program in the editor and my problem was same as above just the client doesn't disconnected from server. but I put that code in a simple C# project and as you mentioned after 5 second server closed the connection. I build the unity project on android and the problem of editor is just solved. I don't know is it my problem or unity problem? Is Unity running code in background although it shows that the program is stopped ? :(

**Comment by RevenantX** [comment] 2017-08-24 10:23
@A-H-B-Gh always call NetManager.Stop() in monobehaviour.
```csharp
    void OnDestroy()
    {
        if(_netClient != null)
            _netClient.Stop();
    }
```
or
```csharp
    void OnApplicationQuit()
    {
        if(_netClient != null)
            _netClient.Stop();
    }
```
LiteNetLib works in another thread. And if you don't call `NetManager.Stop` -> library will work. Thread not closed in editor because editor always running)

**Comment by A-H-B-Gh** [comment] 2017-08-24 10:40
thanks so much.
just solved :))))
I will reopen this issue to show you the result if there is no problem :)

**Closed** 2017-08-24 11:12 UTC
Labels: question

**Comment by Netkicks** [comment] 2020-06-27 23:27
Hi @RevenantX , sorry for resurrecting this old thread. 

There are situations, for example, when a client loses connection, but the Unity client remains open. so OnDestroy() nor OnApplicationQuit() are called. I've tried using server.PingInterval = (X in seconds), and server.DisconnectTimeout on server side, and nothing happens. The server only detects the wrongly disconnected client after a new client joins. Is there a solution for this?

Thanks!

**Comment by RevenantX** [comment] 2020-06-28 12:05
@Netkicks maybe you can create minimal example with problem? Because i cannot reproduce this.
