### ISSUE TITLE
Disconnected peers not removed

### ISSUE THREAD

**Issue by c0nnex** [RevenantX/LiteNetLib#362] opened 2020-04-16 20:24 UTC
I dump regulary 
Logger?.Trace("Connected Clients: {0}/{1}/{2}", _server.GetPeersCount(ConnectionState.Connected), _server.ConnectedPeersCount, _connectedPeers.Count);

_connectedPeers is my own list list of connected peers where peers get removed on disconnect event.
It will output "Connected Clients: 4/4/3" with 3 peers connected.

Had that fixed 2 years ago, but lost my fix when updating to latest master ;)
#161 is back again ;=)

**Comment by RevenantX** [comment] 2020-04-16 20:31
Are you sure that's this not because your list updated on PollEvents, whereas netManager counters updated immediately in other thread? Because test for old bug in executed every build with success.

**Comment by c0nnex** [comment] 2020-04-16 20:36
Am not using pollevents. It's all multithreaded eventdriven

There are no connection events incoming. And it's constantly reporting 4 peers connected

**Comment by c0nnex** [comment] 2020-04-16 20:39
Might it be that the netmanager has a problem if 2 of them are running?
I have one netmanager for server-to-server connection (1 connected) of the shards
and one for client connections (3 connected currently)

**Comment by RevenantX** [comment] 2020-04-16 20:41
You can run tons of netmanagers simultaneously. There is no any problems with this.

**Comment by RevenantX** [comment] 2020-04-16 20:43
Maybe you can create minimal program with bug?

**Comment by c0nnex** [comment] 2020-04-16 20:51
Values after ALL player left the server and definitly no connection is running anymore:
22:50:10.346 | Trace | PureVoice | Connected Clients: 2/2/1

**Comment by RevenantX** [comment] 2020-04-16 21:09
@c0nnex i will investigate this.

**Comment by c0nnex** [comment] 2020-04-16 21:39
Seems to be related to , if a Client-netmanager is recreated. I currently do this on the client if it gets disconnected, because i had problems with the client receiving old data if reusing it after the connection was dropped due e.g. to timeout-

**Comment by RevenantX** [comment] 2020-04-16 21:43
@c0nnex seems that ConnectedPeersCount in some cases not updated fast enough because of some value caches, internally value already volatile but this doesn't helps.

**Comment by c0nnex** [comment] 2020-04-16 21:49
Well server was running 2 hours with us 3 connected, and it reports wrong values for 2 hours ;) I only dump the values every 5 seconds, so it should be updated in the second call by all means if a change occured at same time

**Comment by RevenantX** [comment] 2020-04-16 22:14
@c0nnex ConnectedPeersCount fixed. This was really strange multithreading with caches problem. Bug with ```_server.GetPeersCount(ConnectionState.Connected)``` i cannot reproduce.

**Comment by c0nnex** [comment] 2020-04-17 09:11
I found a place where i kept a peer-Reference, I'll fix that. I'll let you know if problems are fixed now.

**Comment by RevenantX** [comment] 2020-04-17 10:09
@c0nnex peer reference doesn't affect connected count.

**Comment by RevenantX** [comment] 2020-04-19 14:26
@c0nnex should be totally fixed in last commit. Reopen if you found it again

**Closed by RevenantX** 2020-04-19 14:26 UTC
